# Generated by Django 3.2.8 on 2021-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smilemakerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='joke_image_base64',
            field=models.TextField(blank=True),
        ),
    ]
