# Generated by Django 3.2.8 on 2021-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smilemakerapp', '0002_joke_joke_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='joke_json',
            field=models.TextField(blank=True),
        ),
    ]
